#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine


sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
