#!/usr/bin/env bash
# Print 'Best School' ten times, Prints 'Hi' immediately after the ninth time

count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
