#!/usr/bin/env bash
# Checks for the existence of a file or directory and whether it's empty or not

file_name="school"
if [ -e $file_name ]
then
	echo "$file_name file exists"
	if [ -s $file_name ]
	then
		echo "$file_name file is not empty"
	else
		echo "$file_name file is empty"
	fi

	if [ -f $file_name ]
	then
		echo "$file_name is a regular file"
	fi
else
	echo "$file_name file does not exist"
fi
