#!/usr/bin/env bash
# Maps 'localhost' to a new IP address and creates a new mapping for 'facebook.com'

file="/etc/hosts"
sed -i '1s/^/8.8.8.8\tfacebook.com\n/' $file 
sed -i 's/127.0.0.1/127.0.0.2/' $file
